import {
  Box,
  Center,
  Container,
  Text,
  Heading,
  Button,
} from "@chakra-ui/react";
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import React, { useCallback } from "react";

// Polygon only
const injectedConnector = new InjectedConnector({ supportedChainIds: [137] });

const MEMBERSHIP_NFT_CONTRACT_ADDRESS =
  "0x4465aE876e5263cB4Eaf42948723E28bB30C65E8";
const MEMBERSHIP_NFT_TOKEN_ID_REQ = "0";
const MEMBERSHIP_NFT_TOKEN_COUNT_REQ = 1;

const Home: NextPage = () => {
  const router = useRouter();
  const { account, library, activate } = useWeb3React();

  const enterMemberLounge = useCallback(async () => {
    if (library && account) {
      const signer = library.getSigner(account);
      const reqAccess = await fetch("/api/request_access");
      const reqAccessResp = await reqAccess.json();
      const signature = await signer.signMessage(
        `I want to enter the lounge. nonce: ${reqAccessResp.nonce}`
      );
      router.push(`/lounge?signature=${signature}`);
    }
  }, [router, library, account]);

  return (
    <Container>
      <Head>
        <title>thirdweb membership content gate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  */}
      <Center flexDirection="column">
        <Heading>Member Only Lounge</Heading>
        <Text>
          You need to own Membership NFT in order to get access to the website.
        </Text>

        <Text mt={4} textAlign="center">
          You need to have at least{" "}
          <Text fontWeight="bold" as="span">
            {MEMBERSHIP_NFT_TOKEN_COUNT_REQ}{" "}
          </Text>
          <Text as="span">of token id </Text>
          <Text fontWeight="bold" as="span">
            {MEMBERSHIP_NFT_TOKEN_ID_REQ}{" "}
          </Text>
          <Text as="span">from NFT address </Text>
          <Text fontWeight="bold" as="span">
            {MEMBERSHIP_NFT_CONTRACT_ADDRESS}{" "}
          </Text>
        </Text>
      </Center>

      {/* Setup wallet connect button */}
      <Box mt={20} textAlign="center">
        {account ? (
          <>
            <Text>Wallet: {account}</Text>
            <Text mt={4}>
              Do you have access to the member only lounge?{" "}
              <Button onClick={() => enterMemberLounge()}>
                Attempt to Enter Private Lounge
              </Button>
            </Text>
          </>
        ) : (
          <Button onClick={() => activate(injectedConnector)}>
            Connect Wallet (Polygon only)
          </Button>
        )}
      </Box>
    </Container>
  );
};

export default Home;
